### PR TITLE
Feat: add CI with github action

### PR DESCRIPTION
**Pull request by toofff**
While waiting for the PR #31 to be merged I added a CI for the installation of a Bolt project

- [x] Bolt project installation test with docker-compose, PHP 7.4 and MySQL
    - [x] Validate composer.json
    - [x] Run PHP-CS-Fixer
    - [x] Run PHP-CS-Fixer with fix flag
    - [x] Run PHPStan
    - [x] Run Security Checker
    - [x] Check HTTP reachability
        - [x] http://localhost:8080
        - [x] http://localhost:8080/bolt
        - [x] http://localhost:8080/api/contents
        - [x] http://localhost:8080/api/fields
        - [x] http://localhost:8080/api/relations
        - [x] https://localhost:8443
        - [x] https://localhost:8443/bolt
        - [x] https://localhost:8443/api/contents
        - [x] https://localhost:8443/api/fields
        - [x] https://localhost:8443/api/relations
- [x] Bolt project installation test with composer, PHP 7.4 and MySQL
    - [x] Validate composer.json
    - [x] Run PHP-CS-Fixer
    - [x] Run PHP-CS-Fixer with fix flag
    - [x] Run PHPStan
    - [x] Run Security Checker
    - [x] Check HTTP reachability
        - [x] http://localhost:8000
        - [x] http://localhost:8000/bolt
        - [x] http://localhost:8000/api/contents
        - [x] http://localhost:8000/api/fields
        - [x] http://localhost:8000/api/relations

The continuous integration is not yet working on this pull request because nothing is merged into the Bolt repository yet in my opinion. On the other hand you can see it working on [my pull request in my fork](https://github.com/toofff/bolt-project/pull/1/checks)

### CODE REVIEW

**Comment by bobdenotter** [comment]
Hi @toofff Is this written _on top of_ your other PR? As in: Does the other PR need to be merged first, in order for this PR tobe merged.. 

Just asking, because I noticed the `69 changed files` ;-)

**Comment by toofff** [comment]
@bobdenotter it was in order not to pollute the other pull request that I made a second one because it is already big enough like that.

 Yes to merge this one will have to wait until the other is merged

**Comment by toofff** [comment]
@bobdenotter I just finished adding the CI, you will be able [to see the result in my fork](https://github.com/toofff/bolt-project/pull/1).

So we could add cache on the docker images but we would have to add a registry on your side.
We can see that later ;)

**Comment by bobdenotter** [comment]
Hey @toofff ,

I've discussed this, and i think the best course of action is that we'll merge in both of your PR's, and do a short round of beta testing on it. That way we'll be able to iron out the kinks as we go! :-)

The other day it came up that we needed _some_ CI for this repo as well, after my goof with this commit: https://github.com/bolt/project/commit/acd6b72b789b919f87e996244eddbcd3667a435c 🤦

**Comment by toofff** [comment]
Ok, that's fine with me and I have some changes to make on my other pull request that will please everyone.  I'm trying to do this to you tomorrow see Friday

**Comment by toofff** [comment]
Add this commit in #31

**Pull request closed without merging**
