### PR TITLE
fix(dockerfile): change ttf-freefont by fonts-freefont-ttf debian pac…

### PR DESCRIPTION
**Pull request by fabienChaillou**
I try `make docker-install`
This PR fix this errors:
[x] Remove `tf-freefont` and add `fonts-freefont-ttf`
[x] Run in node container `make build-assets`
[x] Move in `cd vendor/bolt/core` && run `npm rebuild node-sass` in node container
[x] Fix `docker-db-create` in php container
[x] Add `make docker-server` in `make docker-install`
[x] Add help in `Makefile`

Error with `tf-freefont`:
bolt-project-error-ttf-freefont

### CODE REVIEW

**Comment by bobdenotter** [comment]
Hi, @fabienChaillou 

I don't really use docker myself, so thanks! 

> [ ] Fix docker-db-create in php container

Let me know when it's updated, and i'll do some monkey-testing! 👍

**Comment by fabienChaillou** [comment]
Hi @bobdenotter ,

I fixed and retest in local `make docker-install` cmd. 

It's 👍 for me.

**Comment by bobdenotter** [comment]
@fabienChaillou Cool! I'll check it out. And also to see if #9 is still needed / correct after this PR. 

Also, I'll apply these changes to the dockerfile in https://github.com/bolt/core

**Comment by doenietzomoeilijk** [comment]
Actually, I'd add the explicit Buster base image in the Dockerfile, to prevent this issue from cropping up *again* on the next Debian release. Like [here](https://github.com/bolt/core/pull/652).

**Pull request merged**
